  INFO root [2019-06-17 15:44:36,898] - 
  INFO root [2019-06-17 15:44:36,898] - -----------------------------------------------------------------------------------------


  INFO root [2019-06-17 15:44:36,899] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-06-17 15:44:36,899] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/HappyPoker_assets/;D:/kbengine/HappyPoker_assets/res/;D:/kbengine/HappyPoker_assets/scripts/
  INFO root [2019-06-17 15:44:36,899] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-06-17 15:44:36,924] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:20013 )
  INFO root [2019-06-17 15:44:36,924] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.56.1:20013, SOMAXCONN=128.
  INFO root [2019-06-17 15:44:36,929] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:56121 )
  INFO root [2019-06-17 15:44:36,929] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:56121, SOMAXCONN=128.
  INFO root [2019-06-17 15:44:36,929] - server-configs:
  INFO root [2019-06-17 15:44:36,929] - 	internalTcpAddr : 192.168.56.1:56121
  INFO root [2019-06-17 15:44:36,930] - 	externalTcpAddr : 192.168.56.1:20013
  INFO root [2019-06-17 15:44:36,930] - 	componentID : 8129652375332859700
  WARN root [2019-06-17 15:44:37,130] - invalid UID(0) <= 0, please check UID for environment! automatically set to 3960.
  INFO root [2019-06-17 15:44:37,226] - Components::findLogger: found logger, addr:192.168.56.1:56045
  INFO root [2019-06-17 15:44:37,227] - Components::addComponent: reset orderLog, uid=3960!
  INFO root [2019-06-17 15:44:37,227] - Components::addComponent[logger], uid=3960, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-06-17 15:44:37,231] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 8129652375332859700. UID: 3960. PID: 4224 ----
  INFO root [2019-06-17 15:44:37,231] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-06-17 15:44:37,232] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-06-17 15:44:37,232] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-06-17 15:44:37,496] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-06-17 15:44:37,496] - Script::install(): KBExtra is successfully!
S_INFO root [2019-06-17 15:44:37,508] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-06-17 15:44:37,509] - TelnetServer server is running on port 31001
  INFO root [2019-06-17 15:44:38,247] - ---- loginapp is running ----
 DEBUG root [2019-06-17 15:44:38,247] - Components::process(): Request for the process of identity...
